# This file contains values from Cookiecutter

default_context:
  project_name: "chat-flock"
  project_description: "Driving Dynamic Multi-Participant Chat Interactions for AI and Human Discourse"
  organization: "chat-flock"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "chat-flock"
  email: "hello@chat-flock.com"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "none"
